[package]
name = "ssh-tunnel-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk = "0.18.1"
libappindicator = "0.9.0"
serde = { version = "1.0.204", features = ["derive"] }
serde_yaml = "0.9.34"
